name: "process_datasets"
namespace: "workflows"
version: "build_main"
argument_groups:
- name: "Inputs"
  arguments:
  - type: "file"
    name: "--input"
    info:
      label: "Common Dataset"
      summary: "A subset of the common dataset."
      slots:
        layers:
        - type: "integer"
          name: "counts"
          description: "Raw counts"
          required: true
        - type: "double"
          name: "normalized"
          description: "Normalized expression values"
          required: true
        obs:
        - type: "string"
          name: "cell_type"
          description: "Cell type information"
          required: true
        - type: "string"
          name: "batch"
          description: "Batch information"
          required: true
        var:
        - type: "boolean"
          name: "hvg"
          description: "Whether or not the feature is considered to be a 'highly variable\
            \ gene'"
          required: true
        - type: "double"
          name: "hvg_score"
          description: "A ranking of the features by hvg."
          required: true
        obsm:
        - type: "double"
          name: "X_pca"
          description: "The resulting PCA embedding."
          required: true
        uns:
        - type: "string"
          name: "dataset_id"
          description: "A unique identifier for the dataset"
          required: true
        - name: "dataset_name"
          type: "string"
          description: "Nicely formatted name."
          required: true
        - type: "string"
          name: "dataset_url"
          description: "Link to the original source of the dataset."
          required: false
        - name: "dataset_reference"
          type: "string"
          description: "Bibtex reference of the paper in which the dataset was published."
          required: false
        - name: "dataset_summary"
          type: "string"
          description: "Short description of the dataset."
          required: true
        - name: "dataset_description"
          type: "string"
          description: "Long description of the dataset."
          required: true
        - name: "dataset_organism"
          type: "string"
          description: "The organism of the sample in the dataset."
          required: false
        - type: "string"
          name: "normalization_id"
          description: "Which normalization was used"
          required: true
    example:
    - "resources_test/common/pancreas/dataset.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Outputs"
  arguments:
  - type: "file"
    name: "--output_train"
    info:
      label: "Training data"
      summary: "The training data in h5ad format"
      slots:
        layers:
        - type: "integer"
          name: "counts"
          description: "Raw counts"
          required: true
        - type: "double"
          name: "normalized"
          description: "Normalized counts"
          required: true
        obs:
        - type: "string"
          name: "label"
          description: "Ground truth cell type labels"
          required: true
        - type: "string"
          name: "batch"
          description: "Batch information"
          required: true
        var:
        - type: "boolean"
          name: "hvg"
          description: "Whether or not the feature is considered to be a 'highly variable\
            \ gene'"
          required: true
        - type: "double"
          name: "hvg_score"
          description: "A ranking of the features by hvg."
          required: true
        obsm:
        - type: "double"
          name: "X_pca"
          description: "The resulting PCA embedding."
          required: true
        uns:
        - type: "string"
          name: "dataset_id"
          description: "A unique identifier for the dataset"
          required: true
        - type: "string"
          name: "normalization_id"
          description: "Which normalization was used"
          required: true
    example:
    - "resources_test/task_template/pancreas/train.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--output_test"
    info:
      label: "Test data"
      summary: "The subset of molecules used for the test dataset"
      slots:
        layers:
        - type: "integer"
          name: "counts"
          description: "Raw counts"
          required: true
        - type: "double"
          name: "normalized"
          description: "Normalized counts"
          required: true
        obs:
        - type: "string"
          name: "batch"
          description: "Batch information"
          required: true
        var:
        - type: "boolean"
          name: "hvg"
          description: "Whether or not the feature is considered to be a 'highly variable\
            \ gene'"
          required: true
        - type: "double"
          name: "hvg_score"
          description: "A ranking of the features by hvg."
          required: true
        obsm:
        - type: "double"
          name: "X_pca"
          description: "The resulting PCA embedding."
          required: true
        uns:
        - type: "string"
          name: "dataset_id"
          description: "A unique identifier for the dataset"
          required: true
        - type: "string"
          name: "normalization_id"
          description: "Which normalization was used"
          required: true
    example:
    - "resources_test/task_template/pancreas/test.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--output_solution"
    info:
      label: "Solution"
      summary: "The solution for the test data"
      slots:
        layers:
        - type: "integer"
          name: "counts"
          description: "Raw counts"
          required: true
        - type: "double"
          name: "normalized"
          description: "Normalized counts"
          required: true
        obs:
        - type: "string"
          name: "label"
          description: "Ground truth cell type labels"
          required: true
        - type: "string"
          name: "batch"
          description: "Batch information"
          required: true
        var:
        - type: "boolean"
          name: "hvg"
          description: "Whether or not the feature is considered to be a 'highly variable\
            \ gene'"
          required: true
        - type: "double"
          name: "hvg_score"
          description: "A ranking of the features by hvg."
          required: true
        obsm:
        - type: "double"
          name: "X_pca"
          description: "The resulting PCA embedding."
          required: true
        uns:
        - type: "string"
          name: "dataset_id"
          description: "A unique identifier for the dataset"
          required: true
        - name: "dataset_name"
          type: "string"
          description: "Nicely formatted name."
          required: true
        - type: "string"
          name: "dataset_url"
          description: "Link to the original source of the dataset."
          required: false
        - name: "dataset_reference"
          type: "string"
          description: "Bibtex reference of the paper in which the dataset was published."
          required: false
        - name: "dataset_summary"
          type: "string"
          description: "Short description of the dataset."
          required: true
        - name: "dataset_description"
          type: "string"
          description: "Long description of the dataset."
          required: true
        - name: "dataset_organism"
          type: "string"
          description: "The organism of the sample in the dataset."
          required: false
        - type: "string"
          name: "normalization_id"
          description: "Which normalization was used"
          required: true
    example:
    - "resources_test/task_template/pancreas/solution.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ";"
resources:
- type: "nextflow_script"
  path: "main.nf"
  is_executable: true
  entrypoint: "run_wf"
- type: "file"
  path: "helper.nf"
info: null
status: "enabled"
dependencies:
- name: "common/check_dataset_schema"
  repository:
    type: "github"
    repo: "openproblems-bio/openproblems-v2"
    tag: "main_build"
- name: "common/extract_metadata"
  repository:
    type: "github"
    repo: "openproblems-bio/openproblems-v2"
    tag: "main_build"
- name: "data_processors/process_dataset"
  repository:
    type: "local"
repositories:
- type: "github"
  name: "openproblems-v2"
  repo: "openproblems-bio/openproblems-v2"
  tag: "main_build"
license: "MIT"
links:
  repository: "https://github.com/openproblems-bio/task_template"
  docker_registry: "ghcr.io"
runners:
- type: "nextflow"
  id: "nextflow"
  directives:
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      lowmem: "memory = 20.Gb"
      midmem: "memory = 50.Gb"
      highmem: "memory = 100.Gb"
      lowcpu: "cpus = 5"
      midcpu: "cpus = 15"
      highcpu: "cpus = 30"
      lowtime: "time = 1.h"
      midtime: "time = 4.h"
      hightime: "time = 8.h"
      veryhightime: "time = 24.h"
  debug: false
  container: "docker"
build_info:
  config: "src/workflows/process_datasets/config.vsh.yaml"
  runner: "nextflow"
  engine: "native"
  output: "target/nextflow/workflows/process_datasets"
  executable: "target/nextflow/workflows/process_datasets/main.nf"
  viash_version: "0.9.0-RC6"
  git_commit: "6c3253ddef5377f7c4e6cc5a0a268c7f573b164a"
  git_remote: "https://github.com/openproblems-bio/task_template"
  dependencies:
  - "target/dependencies/github/openproblems-bio/openproblems-v2/main_build/nextflow/common/check_dataset_schema"
  - "target/dependencies/github/openproblems-bio/openproblems-v2/main_build/nextflow/common/extract_metadata"
  - "target/nextflow/data_processors/process_dataset"
package_config:
  name: "task_template"
  version: "build_main"
  description: "An OpenProblems benchmark task.\n"
  info:
    label: "Template"
    description: "Provide a clear and concise description of your task, detailing\
      \ the specific problem it aims\nto solve. Outline the input data types, the\
      \ expected output, and any assumptions or constraints.\nBe sure to explain any\
      \ terminology or concepts that are essential for understanding the task.\n"
    summary: "A one sentence summary of purpose and methodology. Used for creating\
      \ an overview tables."
    motivation: "Explain the motivation behind your proposed task. Describe the biological\
      \ or computational \nproblem you aim to address and why itâ€™s important. Discuss\
      \ the current state of research in\nthis area and any gaps or challenges that\
      \ your task could help address. This section \nshould convince readers of the\
      \ significance and relevance of your task.\n"
    image: "The name of the image file to use for the component on the website."
    test_resources:
    - type: "s3"
      path: "s3://openproblems-data/resources_test/task_template/"
      dest: "resources_test/task_template"
    - type: "s3"
      path: "s3://openproblems-data/resources_test/common/"
      dest: "resources_test/common"
  viash_version: "0.9.0-RC6"
  source: "src"
  target: "target"
  config_mods:
  - ".runners[.type == \"nextflow\"].config.labels := { lowmem : \"memory = 20.Gb\"\
    , midmem : \"memory = 50.Gb\", highmem : \"memory = 100.Gb\", lowcpu : \"cpus\
    \ = 5\", midcpu : \"cpus = 15\", highcpu : \"cpus = 30\", lowtime : \"time = 1.h\"\
    , midtime : \"time = 4.h\", hightime : \"time = 8.h\", veryhightime : \"time =\
    \ 24.h\" }"
  authors:
  - name: "Kai Waldrant"
    roles:
    - "author"
    - "maintainer"
    info:
      github: "KaiWaldrant"
      orcid: "0009-0003-8555-1361"
      email: "..."
      twitter: "..."
      linkedin: "..."
  keywords:
  - "single-cell"
  - "openproblems"
  - "benchmark"
  license: "MIT"
  organization: "openproblems-bio"
  links:
    repository: "https://github.com/openproblems-bio/task_template"
    docker_registry: "ghcr.io"
    issue_tracker: "https://github.com/openproblems-bio/task_template/issues"
